/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    'node_modules/daisyui/dist/**/*.js',
    'node_modules/react-daisyui/dist/**/*.js',
    './src/**/*.{html,js,jsx}',
  ],

  theme: {
    extend: {},
  },
  // daisyui: {
  //   themes: [
  //     'light',
  //     'dark',
  //     'cupcake',
  //     'bumblebee',
  //     'emerald',
  //     'corporate',
  //     'synthwave',
  //     'retro',
  //     'cyberpunk',
  //     'valentine',
  //     'halloween',
  //     'garden',
  //     'forest',
  //     'aqua',
  //     'lofi',
  //     'pastel',
  //     'fantasy',
  //     'wireframe',
  //     'black',
  //     'luxury',
  //     'dracula',
  //     'cmyk',
  //     'autumn',
  //     'business',
  //     'acid',
  //     'lemonade',
  //     'night',
  //     'coffee',
  //     'winter',
  //   ],
  // },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
};
